name: Generate Press Release

on:
  push:
    branches:
      - main

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install openai
          pip install smtplib # This line is unnecessary because smtplib is part of the standard library
          pip install email # This line is unnecessary because email is part of the standard library

      - name: Generate and Send Press Release
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          source venv/bin/activate
          python generate_and_send_press_release.py
